### ISSUE TITLE
Can't login/ configuration problem  -  "TypeError: Only absolute URLs are supported"

### ISSUE THREAD

**Issue by s-gbz** [calendso/docker#5]
Hey guys,
thanks for your effort in brining calendso to Docker! :heart: 
I'm currently writing a blog post/ documentation material how to setup calendso front to finish on a server :memo: 

However, I'm stuck at the login screen without further error messages and am slowly exhausting my knowledge.
Please feel free to move the issue into calendso's main repository if you see fit.

Let me know if I can provide any more context or details.

# The situation
I'm using **nginx** and have SSL access to the login page via `https://date.mysite.com`.

# The problem
Authentication can't be processed:
```
calendso_1  | [next-auth][error][client_fetch_error]
calendso_1  | https://next-auth.js.org/errors#client_fetch_error session TypeError: Only absolute URLs are supported
calendso_1  |     at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
calendso_1  |     at /app/node_modules/node-fetch/lib/index.js:1410:19
calendso_1  |     at new Promise (<anonymous>)
calendso_1  |     at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
calendso_1  |     at _callee9$ (/app/node_modules/next-auth/dist/client/index.js:625:20)
calendso_1  |     at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:63:40)
calendso_1  |     at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:293:22)
calendso_1  |     at Generator.next (/app/node_modules/regenerator-runtime/runtime.js:118:21)
calendso_1  |     at asyncGeneratorStep (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
calendso_1  |     at _next (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

This is what Firefox (89.0.2. Linux) provides me with after I try to login:

![image](https://user-images.githubusercontent.com/23424538/125448390-ab36024d-a9ae-49db-8068-7ee84d0af348.png)

Strangely, Chromium doesn't even get as far as Firefox and totally messes up the redirection 

![image](https://user-images.githubusercontent.com/23424538/125451242-e91c8d2c-669d-4f3b-b7e3-e7c7e6669e34.png)

# The configuration 

## env
The insides of . `env`

```
BASE_URL="https://date.mysite.com"
NEXTAUTH_URL="https://date.mysite.com"
# Tried providing this as well -> NEXT_PUBLIC_NEXTAUTH_URL="http://date.mysite.com/api/auth"
```

I tried all possible combinations with/ without `http`/ `https`.
Some combinations lead to `https://'https//date.mysite.com'/signin?csrf=true`

## nginx
The relevant aspects of nginx include a redirect to https & hiding the port from the ip.
```
server {
            listen [::]:443 ssl ipv6only=on; # managed by Certbot
            listen 443 ssl; # managed by Certbot
            ssl_certificate /path/to/your/cert.pem;        
        	ssl_certificate_key /path/to/your/private/key.pem;
            include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
            ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

            location / {
                proxy_pass http://127.0.0.1:3000;
                proxy_set_header Host $host; proxy_set_header
                X-Real-IP $remote_addr; proxy_set_header
                X-Forwarded-For $proxy_add_x_forwarded_for;
            }

        }

        server {
            listen 80 default_server;
            return 301 https://$host$request_uri;
        }
```

## docker-compose
I'm running the docker-compose file with an addition to the networks setting to make the database accessible to calendso

```
networks:
  customnet:
    name: custom_network
```

Here's the full `docker-compose` file 

```
version: '3.5'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - customnet
  calendso:
    build: .
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
    env_file: .env
    depends_on:
      - db
    networks:
      - customnet
volumes:
  database-data:

networks:
  customnet:
    name: custom_network
```

---
# Server start
Lastly, the server starts as it (hopefully) should

```
calendso_1  | + yarn start
calendso_1  | yarn run v1.22.5
calendso_1  | $ next start
calendso_1  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
calendso_1  | info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
```
